# Generated by Django 4.1 on 2022-08-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="date_ordered", new_name="start_date",
        ),
        migrations.RemoveField(model_name="order", name="transaction_id",),
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="ordered_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
